    LIST P=16F887
    #include "p16f887.inc"
    
    __CONFIG _CONFIG1, _XT_OSC & _WDTE_OFF & _MCLRE_ON & _LVP_OFF

DISP_VAL	    EQU 0
DISP_UMB	    EQU 1
DISP_TCL1	    EQU 2
DISP_TCL2	    EQU 3
DISP_OFF	    EQU 12
DISP_D_LITERAL	    EQU 10
DISP_B_LITERAL	    EQU 11
CLEAR_RC4_RC1_MASK  EQU B'11100001'
NTECL_ERR	    EQU 0xFF
NTECL_BACK	    EQU 10
NTECL_SET	    EQU 11
    
    CBLOCK 0X20
	COUNTER_DISPLAY
	DELAY1
	DELAY2
	DELAY3
	DELAY4
	W_TEMP
	STATUS_TEMP
	DECENAS
	UNIDAD
	NTECL
	UMBRAL_BCD
	TEMP_UMBRAL_BCD
	DISP4
	DISP3
	DISP2
	DISP1
	DISP_STATE
	TEMP_ON_DISP_MASK
    ENDC
      
CFG_UART_TX	MACRO
		BANKSEL PORTC
		BCF	PORTC, RC6
		BANKSEL TRISC
		BCF	TRISC, TRISC6 ; RC6 DIGITAL OUT
		BANKSEL RCSTA
		BSF	RCSTA, SPEN ; RC6 TX MODE
		BANKSEL TXSTA
		BSF	TXSTA, TXEN ; TX EN
		BCF	TXSTA, SYNC ; ASYNC
		BSF	TXSTA, BRGH ; HIGH SPEED
		BANKSEL BAUDCTL
		BCF	BAUDCTL, BRG16 ; 8 BIT
		BANKSEL SPBRG
		MOVLW	.25
		MOVWF	SPBRG ; 9600 Bd
		ENDM

CFG_ADC		MACRO
		BANKSEL ADCON1
		BCF     ADCON1, ADFM       ; 0 = justificado a la izquierda
		BANKSEL ADCON0
		MOVLW   b'10010101'        ; ADCS1=1 ADCS0=0 CHS=0101 (AN5 = RE0) ADON=1
		MOVWF   ADCON0
		ENDM
    
CFG_INT_ADC	MACRO
		BANKSEL	INTCON
		MOVLW	b'11000000'	;Habilita interrupciones globales
		MOVWF	INTCON		;Habilita int por perifericos
		BANKSEL	PIE1
		MOVWF	PIE1		;Habilita int por ADC (fin de conversion)
		ENDM

CFG_DISP	MACRO
		BANKSEL TRISD		; (PORTD es digital por default)
		CLRF	TRISD		; PORTD Salida
		BANKSEL PORTD
		CLRF	PORTD		; PORTD estado bajo
		BANKSEL TRISC
		BCF TRISC, TRISC4
		BCF TRISC, TRISC3
		BCF TRISC, TRISC2
		BCF TRISC, TRISC1
		BANKSEL PORTC
		MOVFW PORTC
		ANDLW CLEAR_RC4_RC1_MASK
		IORLW B'00001110' ; rc3, rc2, rc1 en 1 rc4 on
		MOVWF PORTC
		BCF STATUS, RP0
		BCF STATUS, RP1
		MOVLW DISP_VAL
		MOVWF DISP_STATE
		MOVLW DISP_OFF
		MOVWF DISP4
		MOVWF DISP3
		MOVLW DISP_D_LITERAL
		MOVWF DISP2
		MOVLW DISP_B_LITERAL
		MOVWF DISP1
		ENDM

CFG_TECLADO	MACRO
		BANKSEL ANSELH		
		CLRF	ANSELH ; PORTB digital
		BANKSEL PORTB
		MOVLW B'11110000' ; PORTB estado bajo
		MOVWF PORTB
		BANKSEL OPTION_REG
		BCF OPTION_REG, NOT_RBPU ;Habilito resistencias internas de pull-up
		BANKSEL TRISB
		MOVLW B'00001111'	
		MOVWF TRISB ; B<7,4>Salidas, B<3,0>Entradas
		BANKSEL IOCB
		MOVLW B'11111111'
		MOVWF IOCB
		BANKSEL INTCON
		BSF INTCON, RBIE ; Habilito interrupciones externas por PORTB
		BCF STATUS, RP0
		BCF STATUS, RP1
		CLRF NTECL
		ENDM

    ORG 0X00
    GOTO INICIO_PRUEBA_TECL_DISPLAY
    ORG 0X04
    GOTO ISR_INICIO
    ORG 0X05
	
INICIO_PRUEBA_TECL_DISPLAY:
    CFG_DISP
    CFG_TECLADO
    BANKSEL INTCON
    BSF INTCON, GIE
    BCF STATUS, RP0
    BCF STATUS, RP1
    MOVLW 4
    MOVWF DECENAS
    MOVLW 5
    MOVWF UNIDAD
    CALL REFRESH_DISPLAYS
    GOTO $-1
	
INICIO_PRUEBA_EUSART:
    CFG_UART_TX
    BCF STATUS, RP0
    BCF STATUS, RP1
LOOP_PRUEBA:
    MOVLW .1
    MOVWF DECENAS
    MOVLW .1
    MOVWF UNIDAD
    CALL TX_ADQ_ASCII
    
    MOVLW .1
    MOVWF DECENAS
    MOVLW .2
    MOVWF UNIDAD
    CALL TX_ADQ_ASCII
    
    MOVLW .2
    MOVWF DECENAS
    MOVLW .1
    MOVWF UNIDAD
    CALL TX_ADQ_ASCII
    
    MOVLW .1
    MOVWF DECENAS
    MOVLW .1
    MOVWF UNIDAD
    CALL TX_ADQ_ASCII
    GOTO LOOP_PRUEBA
    GOTO $

INICIO_PRUEBA_ADC
	CFG_DISP
    CFG_ADC
    CFG_INT
    ;Delay de adquisición (20us aprox.)
    CALL    Delay_50us
    BANKSEL ADCON0
    BSF     ADCON0, GO_DONE     ; Iniciar conversión  
    GOTO    INICIO_PRUEBA_ADC
    
Delay_50us
    BANKSEL ContadorDelay
    movlw   d'12'
    movwf   ContadorDelay
D1
    NOP
    NOP
    DECFSZ  ContadorDelay, F
    GOTO    D1
    RETURN 

ISR_INICIO:
    MOVWF W_TEMP
    SWAPF STATUS, W
    MOVWF STATUS_TEMP
    BTFSC INTCON, RBIF
    GOTO ISR_TECL
    BTFSC PIR1, ADIF
    GOTO  ISR_ADC
    GOTO ISR_FIN
	    
ISR_FIN:
    SWAPF STATUS_TEMP, W
    MOVWF STATUS
    SWAPF W_TEMP, F
    SWAPF W_TEMP, W
    RETFIE 

ISR_ADC:
    BANKSEL ADCON0
    ;BCF	    ADCON0, ADON   ; DESHABILITO ADC
    BCF	    PIR1,ADIF	   ; Bajo bandera
    BANKSEL ADRESH
    MOVFW   ADRESH         ; Solo 8 bits
    MOVWF   ResultadoH	
    CALL    AD_BCD	   ; Convierte a binario
    CALL    REFRESH_DISPLAYS
    GOTO    ISR_FIN

ISR_TECL:
    BCF INTCON, RBIF 
    BCF INTCON, RBIE      ; deshabilita mientras atiende
    MOVF PORTB, W         ; lectura para resetear latch
    CALL TECL_PRESS
    CALL TECL_LOAD
    CLRF PORTB
    BCF INTCON, RBIF
    BSF INTCON, RBIE
    GOTO ISR_FIN
    
TECL_PRESS:
    CLRF NTECL
    MOVLW B'01110000'
    MOVWF PORTB
    CALL DELAY_20MS
    GOTO TEST_COL
	    
TEST_COL:
    INCF NTECL, F
    BTFSS PORTB, RB3
    GOTO TECL_DELAY
    INCF NTECL, F
    BTFSS PORTB, RB2
    GOTO TECL_DELAY
    INCF NTECL, F
    BTFSS PORTB, RB1
    GOTO TECL_DELAY
    GOTO TEST_FIL
	    
TEST_FIL:    
    BTFSS PORTB, RB4
    GOTO TECL_RST ;si ya probe todo termino la interrupcion
    BSF STATUS, C ;sino recorro la siguiente fila
    RRF PORTB
    GOTO TEST_COL ;(columna por columna)
    RETURN
	    
TECL_RST:    
    CLRF NTECL
    CLRF PORTB
    BCF INTCON, RBIF
    RETURN
	    
TECL_DELAY:  
    CALL DELAY_20MS
    BTFSS PORTB, RB3 ;loops antirrebote por software
    GOTO $-1
    BTFSS PORTB, RB2
    GOTO $-1
    BTFSS PORTB, RB1
    GOTO $-1
    BTFSS PORTB, RB0
    GOTO $-1
    BCF INTCON, RBIF ;bajo bandera de interrupcion
    CLRF PORTB ;limpio puerto
    RETURN
	    
TECL_LOAD:
    CALL CONVERT_NTECL
    MOVWF NTECL
    MOVLW NTECL_ERR
    SUBWF NTECL, W
    BTFSC STATUS,Z
    RETURN
    MOVLW DISP_VAL
    SUBWF DISP_STATE, W
    BTFSC STATUS,Z
    GOTO FROM_DISP_VAL
    MOVLW DISP_UMB
    SUBWF DISP_STATE, W
    BTFSC STATUS,Z
    GOTO FROM_DISP_UMB
    MOVLW DISP_TCL1
    SUBWF DISP_STATE, W
    BTFSC STATUS,Z
    GOTO FROM_DISP_TCL1
    MOVLW DISP_TCL2
    SUBWF DISP_STATE, W
    BTFSC STATUS,Z
    GOTO FROM_DISP_TCL2
    RETURN

FROM_DISP_VAL:
    MOVLW NTECL_BACK
    SUBWF NTECL, W
    BTFSC STATUS, Z
    GOTO CLEAR_ALARM
    MOVLW NTECL_SET
    SUBWF NTECL, W
    BTFSC STATUS, Z
    GOTO LOAD_DISP_UMB
    RETURN
    
FROM_DISP_UMB:
    MOVLW NTECL_BACK
    SUBWF NTECL, W
    BTFSC STATUS, Z
    GOTO LOAD_DISP_VAL
    MOVLW NTECL_SET
    SUBWF NTECL, W
    BTFSC STATUS, Z
    GOTO LOAD_DISP_VAL
    GOTO LOAD_TCL1
    
FROM_DISP_TCL1:
    MOVLW NTECL_SET
    SUBWF NTECL, W
    BTFSC STATUS, Z
    GOTO CONFIRM_TCL
    MOVLW NTECL_BACK
    SUBWF NTECL, W
    BTFSC STATUS, Z
    GOTO LOAD_DISP_VAL
    GOTO LOAD_TCL2
    
FROM_DISP_TCL2:
    MOVLW NTECL_SET
    SUBWF NTECL, W
    BTFSC STATUS, Z
    GOTO CONFIRM_TCL
    MOVLW NTECL_BACK
    SUBWF NTECL, W
    BTFSC STATUS, Z
    GOTO LOAD_DISP_VAL
    RETURN

CLEAR_ALARM:
    BCF PORTC, RC0
    RETURN

LOAD_DISP_VAL:
    MOVFW DECENAS
    MOVWF DISP4
    MOVFW UNIDAD
    MOVWF DISP3
    MOVLW DISP_D_LITERAL
    MOVWF DISP2
    MOVLW DISP_B_LITERAL
    MOVWF DISP1
    MOVLW DISP_VAL
    MOVWF DISP_STATE
    CLRF TEMP_UMBRAL_BCD
    RETURN    

LOAD_DISP_UMB:
    SWAPF UMBRAL_BCD, W
    ANDLW 0x0F
    MOVWF DISP4
    MOVFW UMBRAL_BCD
    ANDLW 0x0F
    MOVWF DISP3
    MOVLW DISP_D_LITERAL
    MOVWF DISP2
    MOVLW DISP_B_LITERAL
    MOVWF DISP1
    MOVLW DISP_UMB
    MOVWF DISP_STATE
    RETURN
    
LOAD_TCL1:
    MOVFW NTECL
    MOVWF TEMP_UMBRAL_BCD
    SWAPF TEMP_UMBRAL_BCD, W
    ANDLW 0x0F
    MOVWF DISP4
    MOVFW TEMP_UMBRAL_BCD
    ANDLW 0x0F
    MOVWF DISP3
    MOVLW DISP_D_LITERAL
    MOVWF DISP2
    MOVLW DISP_B_LITERAL
    MOVWF DISP1
    MOVLW DISP_TCL1
    MOVWF DISP_STATE
    RETURN
    
LOAD_TCL2:
    SWAPF TEMP_UMBRAL_BCD, W
    IORWF NTECL, W
    MOVWF TEMP_UMBRAL_BCD
    SWAPF TEMP_UMBRAL_BCD, W
    ANDLW 0x0F
    MOVWF DISP4
    MOVFW TEMP_UMBRAL_BCD
    ANDLW 0x0F
    MOVWF DISP3
    MOVLW DISP_D_LITERAL
    MOVWF DISP2
    MOVLW DISP_B_LITERAL
    MOVWF DISP1
    MOVLW DISP_TCL2
    MOVWF DISP_STATE
    RETURN
    
CONFIRM_TCL:
    MOVFW TEMP_UMBRAL_BCD
    MOVWF UMBRAL_BCD
    GOTO LOAD_DISP_VAL

CONVERT_NTECL:
    MOVFW NTECL
    ADDWF PCL, F
    RETLW NTECL_ERR
    RETLW 1
    RETLW 2
    RETLW 3
    RETLW 4
    RETLW 5
    RETLW 6
    RETLW 7
    RETLW 8
    RETLW 9
    RETLW NTECL_BACK
    RETLW 0
    RETLW NTECL_SET

AD_BCD:	    CLRF    CENTENA
	    CLRF    DECENA
	    CLRF    UNIDAD
TEST_CENTENA MOVLW  d'100' 
	    SUBWF   ResultadoH,0   ;ResultadoH - 100 -> W
	    BTFSC   STATUS,C
	    GOTO    ADD_CENTENA	    ;si ResultadoH>100 sumo CENTENA    
TEST_DECENA MOVLW   d'10' 
	    SUBWF   ResultadoH,0    ;ResultadoH - 10 -> W
	    BTFSC   STATUS,C
	    GOTO    ADD_DECENA	    ;si ADRESH>10 sumo DECENA
	    MOVFW   ResultadoH
	    MOVWF   UNIDAD	    ;sino ADRESH va a UNIDAD
	    RETURN    
ADD_CENTENA BCF	    STATUS,C
	    MOVWF   ResultadoH	    ;guardo el resto
	    INCF    CENTENA	    ;cuento una centena
	    GOTO    TEST_CENTENA    ;sigo buscando centenas
ADD_DECENA  BCF	    STATUS,C
	    MOVWF   ResultadoH	    ;guardo el resto
	    INCF    DECENA	    ;cuento una decena
	    GOTO    TEST_DECENA	    ;sigo buscando decenas

REFRESH_DISPLAYS:
    MOVLW DISP_VAL
    SUBWF DISP_STATE, W
    BTFSC STATUS, Z
    CALL LOAD_LAST_ADQ
    MOVLW .4
    MOVWF COUNTER_DISPLAY
LOOP_DISPLAY:
    MOVLW .4
    SUBWF COUNTER_DISPLAY, W
    BTFSC STATUS, Z
    CALL LOAD_DISPLAY4
    MOVLW .3
    SUBWF COUNTER_DISPLAY, W
    BTFSC STATUS, Z
    CALL LOAD_DISPLAY3
    MOVLW .2
    SUBWF COUNTER_DISPLAY, W
    BTFSC STATUS, Z
    CALL LOAD_DISPLAY2
    MOVLW .1
    SUBWF COUNTER_DISPLAY, W
    BTFSC STATUS, Z
    CALL LOAD_DISPLAY1
    DECFSZ COUNTER_DISPLAY, F
    GOTO LOOP_DISPLAY
    RETURN
    
LOAD_DISPLAY4:
    MOVF COUNTER_DISPLAY, W
    CALL TABLE_ON_DISPLAY_AC
    MOVWF TEMP_ON_DISP_MASK
    MOVFW PORTC
    ANDLW CLEAR_RC4_RC1_MASK
    IORWF TEMP_ON_DISP_MASK, W
    MOVWF PORTC
    MOVFW DISP4
    CALL TABLE_DECO_DISPLAY_AC
    MOVWF PORTD
    CALL DELAY_5MS
    RETURN
    
LOAD_DISPLAY3:	
    MOVF COUNTER_DISPLAY, W
    CALL TABLE_ON_DISPLAY_AC
    MOVWF TEMP_ON_DISP_MASK
    MOVFW PORTC
    ANDLW CLEAR_RC4_RC1_MASK
    IORWF TEMP_ON_DISP_MASK, W
    MOVWF PORTC
    MOVFW DISP3
    CALL TABLE_DECO_DISPLAY_AC
    MOVWF PORTD
    CALL DELAY_5MS
    RETURN
    
LOAD_DISPLAY2:	
    MOVF COUNTER_DISPLAY, W
    CALL TABLE_ON_DISPLAY_AC
    MOVWF TEMP_ON_DISP_MASK
    MOVFW PORTC
    ANDLW CLEAR_RC4_RC1_MASK
    IORWF TEMP_ON_DISP_MASK, W
    MOVWF PORTC
    MOVFW DISP2
    CALL TABLE_DECO_DISPLAY_AC
    MOVWF PORTD
    CALL DELAY_5MS
    RETURN
    
LOAD_DISPLAY1:	
    MOVF COUNTER_DISPLAY, W
    CALL TABLE_ON_DISPLAY_AC
    MOVWF TEMP_ON_DISP_MASK
    MOVFW PORTC
    ANDLW CLEAR_RC4_RC1_MASK
    IORWF TEMP_ON_DISP_MASK, W
    MOVWF PORTC
    MOVFW DISP1
    CALL TABLE_DECO_DISPLAY_AC
    MOVWF PORTD
    CALL DELAY_5MS
    RETURN
    
LOAD_LAST_ADQ:
    MOVFW DECENAS
    MOVWF DISP4
    MOVFW UNIDAD
    MOVWF DISP3
    RETURN

DELAY_5MS:	
    MOVLW   D'65'
    MOVWF   DELAY1
LOOPA:		
    MOVLW   D'25'
    MOVWF   DELAY2
LOOPB:		
    DECFSZ  DELAY2,F
    GOTO    LOOPB
    DECFSZ  DELAY1,F
    GOTO    LOOPA
    RETURN
		
DELAY_20MS:	
    MOVLW   D'255'
    MOVWF   DELAY3
LOOP1:		
    MOVLW   D'26'
    MOVWF   DELAY4
LOOP2:		
    DECFSZ  DELAY4,F
    GOTO    LOOP2
    DECFSZ  DELAY3,F
    GOTO    LOOP1
    RETURN

TABLE_ON_DISPLAY_AC ADDWF PCL, F
		    RETLW b'00000000'
		    RETLW b'00011100' ;DISP1 ON
		    RETLW b'00011010' ;DISP2 ON
		    RETLW b'00010110' ;DISP3 ON
		    RETLW b'00001110' ;DISP4 ON
	    
TABLE_DECO_DISPLAY_AC	ADDWF PCL, F
			RETLW b'10100000' ;0
			RETLW b'11111001' ;1
			RETLW b'10100100' ;2
			RETLW b'10110000' ;3
			RETLW b'10011001' ;4
			RETLW b'10010010' ;5
			RETLW b'10000010' ;6
			RETLW b'11111000' ;7
			RETLW b'10000000' ;8
			RETLW b'10011000' ;9
			RETLW b'10100001' ;d
			RETLW b'10000011' ;b
			RETLW b'11111111' ;off
			

UART_TX:
    BANKSEL TXSTA
    BTFSS   TXSTA, TRMT
    GOTO $-1
    BANKSEL TXREG
    MOVWF TXREG
    RETURN
    

TX_ADQ_ASCII:
    MOVFW DECENAS
    ADDLW .48
    CALL UART_TX
    MOVFW UNIDAD
    ADDLW .48
    CALL UART_TX
    MOVLW .10 ; LF
    CALL UART_TX
    MOVLW .13 ; CR
    CALL UART_TX
    RETURN
			

    END







