LIST P=16F887
#include "p16f887.inc"

__CONFIG _CONFIG1, _XT_OSC & _WDTE_OFF & _MCLRE_ON & _LVP_OFF
    
CBLOCK 0x20
    COUNTER
    COUNTER_MAX
    DELAY1
    DELAY2
    TICK_20MS
    TICK_MAX
    COUNTER_DISPLAY
    NTECLA4
    NTECLA3
    NTECLA2
    NTECLA1
    BLINKING
ENDC
    
    ORG 0X00
    GOTO INICIO
    ORG 0X05

TABLE_ON_DISPLAY_AC
    ADDWF PCL, F
    RETLW b'11111111'
    RETLW b'11111110'
    RETLW b'11111101'
    RETLW b'11111011'
    RETLW b'11110111'
	    
TABLE_DECO_DISPLAY_AC	
		ADDWF PCL, F
		RETLW b'11000000'
		RETLW b'11111001'
		RETLW b'10100100'
		RETLW b'10110000'
		RETLW b'10011001'
		RETLW b'10010010'
		RETLW b'10000010'
		RETLW b'11111000'
		RETLW b'10000000'
		RETLW b'10011000'
		RETLW b'11111111'
		RETLW b'10000000'

INICIO
    BANKSEL PORTA
    CLRF PORTA
    BANKSEL ANSEL		; A0 a A3 Digitales
    BCF ANSEL, ANS0
    BCF ANSEL, ANS1
    BCF ANSEL, ANS2
    BCF ANSEL, ANS3		; Al final usasmos 4 displays
    CLRF ANSELH
    BANKSEL TRISA		; A0 a A3 Salidas
    BCF TRISA, TRISA0
    BCF TRISA, TRISA1
    BCF TRISA, TRISA2
    BCF TRISA, TRISA3	
    BANKSEL TRISD
    CLRF TRISD			; PORTD como Salida
    BANKSEL PORTD
    CLRF PORTD			; Limpio salida
    MOVLW   .10
    MOVWF   COUNTER_MAX ; Cuenta maximo a 10
    MOVLW .5
    MOVWF TICK_MAX
    CLRF NTECLA4
    CLRF NTECLA3
    CLRF NTECLA2
    CLRF NTECLA1
    
LOOP	CALL UPDATE_DISPLAYS
	CALL REFRESH_DISPLAYS
	GOTO LOOP
	
	
UPDATE_DISPLAYS
	CALL INC_DISPLAYS
	BTFSS NTECLA3, 0
	RETURN
	BTFSS NTECLA1, 0
	RETURN
	CALL BLINK
	
BLINK
	MOVLW .10
	MOVWF NTECLA4
	MOVWF NTECLA3
	MOVWF NTECLA2
	MOVWF NTECLA1
	CALL REFRESH_DISPLAYS
	MOVLW .11
	MOVWF NTECLA4
	MOVWF NTECLA3
	MOVWF NTECLA2
	MOVWF NTECLA1
	CALL REFRESH_DISPLAYS
	GOTO BLINK2

	
INC_DISPLAYS
	MOVFW TICK_20MS
	SUBWF TICK_MAX, W
	BTFSS STATUS, Z
	RETURN
	CLRF	TICK_20MS
	INCF	NTECLA1
	MOVFW	NTECLA1
	SUBWF	COUNTER_MAX, W
	BTFSS	STATUS, Z
	RETURN
	CLRF	NTECLA1
	INCF	NTECLA2
	MOVFW	NTECLA2
	SUBWF	COUNTER_MAX, W
	BTFSS	STATUS, Z
	RETURN
	CLRF	NTECLA2
	INCF	NTECLA3
	MOVFW	NTECLA3
	SUBWF	COUNTER_MAX, W
	BTFSS	STATUS, Z
	RETURN
	CLRF	NTECLA3
	INCF	NTECLA4
	MOVFW	NTECLA4
	SUBWF	COUNTER_MAX, W
	BTFSS	STATUS, Z
	RETURN
	CLRF	NTECLA4
	RETURN
	
	
REFRESH_DISPLAYS
	MOVLW .4
	MOVWF COUNTER_DISPLAY
	LOOP_DISPLAY
	    MOVLW .4
	    SUBWF COUNTER_DISPLAY, W
	    BTFSC STATUS, Z
	    CALL LOAD_DISPLAY4
	    MOVLW .3
	    SUBWF COUNTER_DISPLAY, W
	    BTFSC STATUS, Z
	    CALL LOAD_DISPLAY3
	    MOVLW .2
	    SUBWF COUNTER_DISPLAY, W
	    BTFSC STATUS, Z
	    CALL LOAD_DISPLAY2
	    MOVLW .1
	    SUBWF COUNTER_DISPLAY, W
	    BTFSC STATUS, Z
	    CALL LOAD_DISPLAY1
	    DECFSZ COUNTER_DISPLAY, F
	    GOTO LOOP_DISPLAY
	    INCF TICK_20MS, F
	    RETURN
    
LOAD_DISPLAY4
    MOVF COUNTER_DISPLAY, W
    CALL TABLE_ON_DISPLAY_AC
    MOVWF PORTA
    MOVFW NTECLA4
    CALL TABLE_DECO_DISPLAY_AC
    MOVWF PORTD
    CALL DELAY_5MS
    MOVLW b'11111111'
    MOVWF PORTA
    RETURN
    
LOAD_DISPLAY3
    MOVF COUNTER_DISPLAY, W
    CALL TABLE_ON_DISPLAY_AC
    MOVWF PORTA
    MOVFW NTECLA3
    CALL TABLE_DECO_DISPLAY_AC
    MOVWF PORTD
    CALL DELAY_5MS
    MOVLW b'11111111'
    MOVWF PORTA
    RETURN
    
LOAD_DISPLAY2
    MOVF COUNTER_DISPLAY, W
    CALL TABLE_ON_DISPLAY_AC
    MOVWF PORTA
    MOVFW NTECLA2
    CALL TABLE_DECO_DISPLAY_AC
    MOVWF PORTD
    CALL DELAY_5MS
    MOVLW b'11111111'
    MOVWF PORTA
    RETURN
    
LOAD_DISPLAY1
    MOVF COUNTER_DISPLAY, W
    CALL TABLE_ON_DISPLAY_AC
    MOVWF PORTA
    MOVFW NTECLA1
    CALL TABLE_DECO_DISPLAY_AC
    MOVWF PORTD
    CALL DELAY_5MS
    MOVLW b'11111111'
    MOVWF PORTA
    RETURN

DELAY_5MS	MOVLW   D'65'
		MOVWF   DELAY1
	LOOPA	MOVLW   D'25'
		MOVWF   DELAY2
	LOOPB	DECFSZ  DELAY2,F
		GOTO    LOOPB
		DECFSZ  DELAY1,F
		GOTO    LOOPA
		RETURN
	    
	END

