LIST P=16F887
#include "p16f887.inc"
     
__CONFIG _CONFIG1, _XT_OSC & _WDTE_OFF & _MCLRE_ON & _LVP_OFF

CBLOCK  0X20
    DELAY1 
    DELAY2 
    DELAY3
    COUNTER_MAX
    COUNTER
ENDC
	    
	ORG 0x00
	GOTO INICIO
INICIO	ORG 0x05 
	

	BANKSEL ANSEL 
	BCF	ANSEL, ANS0
	BANKSEL TRISA
	BCF	TRISA, TRISA0
	BANKSEL PORTA 
	BCF	PORTA, RA0
	BANKSEL TRISD
	CLRF	TRISD
	BANKSEL PORTD
	CLRF	PORTD
	MOVLW   .10
	MOVWF   COUNTER_MAX
	CLRF    COUNTER

LOOP		CALL REFRESH_DISP
		CALL INC_COUNTER
		CALL DELAY_1s
		GOTO LOOP

DELAY_1s	MOVLW   D'255'
		MOVWF   DELAY1
	LOOPA	MOVLW   D'245'
		MOVWF   DELAY2
	LOOPB	MOVLW   D'4'
		MOVWF   DELAY3
	LOOPC	DECFSZ  DELAY3,F
		GOTO    LOOPC
		DECFSZ  DELAY2,F
		GOTO    LOOPB
		DECFSZ  DELAY1,F
		GOTO    LOOPA
		RETURN

REFRESH_DISP	MOVF	COUNTER,W
		CALL	TABLE_ENCODE
		MOVWF	PORTD
		RETURN

INC_COUNTER	
		INCF	COUNTER
		MOVFW	COUNTER
		SUBWF	COUNTER_MAX, W
		BTFSS	STATUS, Z
		RETURN
		CLRF	COUNTER
		RETURN

TABLE_ENCODE	ADDWF PCL, F
		RETLW b'11000000'
		RETLW b'11111001'
		RETLW b'10100100'
		RETLW b'10110000'
		RETLW b'10011001'
		RETLW b'10010010'
		RETLW b'10000010'
		RETLW b'11111000'
		RETLW b'10000000'
		RETLW b'10011000'
		
END