LIST P=16F887
#include "p16f887.inc"
    
__CONFIG _CONFIG1, _XT_OSC & _WDTE_OFF & _MCLRE_ON & _LVP_OFF

CBLOCK 0X20
    COUNTER_DISPLAY
    DELAY1
    DELAY2
    NTECLA4
    NTECLA3
    NTECLA2
    NTECLA1
    W_TEMP
    STATUS_TEMP
ENDC
    
ORG 0X00
    GOTO INICIO
ORG 0X04
    GOTO ISR_INICIO
ORG 0X05
    
INICIO	BANKSEL ANSELH
	CLRF	ANSELH
	
LOOP	CALL REFRESH_DISPLAYS
	GOTO LOOP
	
ISR_INICIO  MOVWF W_TEMP
	    SWAPF STATUS, W
	    MOVWF STATUS_TEMP
	    ; (ISR)
	    SWAPF STATUS_TEMP, W
	    MOVWF STATUS
	    SWAPF W_TEMP, F
	    SWAPF W_TEMP, W
	    RETFIE

REFRESH_DISPLAYS    MOVLW .4
		    MOVWF COUNTER_DISPLAY
    LOOP_DISPLAY    MOVLW .4
		    SUBWF COUNTER_DISPLAY, W
		    BTFSC STATUS, Z
		    CALL LOAD_DISPLAY4
		    MOVLW .3
		    SUBWF COUNTER_DISPLAY, W
		    BTFSC STATUS, Z
		    CALL LOAD_DISPLAY3
		    MOVLW .2
		    SUBWF COUNTER_DISPLAY, W
		    BTFSC STATUS, Z
		    CALL LOAD_DISPLAY2
		    MOVLW .1
		    SUBWF COUNTER_DISPLAY, W
		    BTFSC STATUS, Z
		    CALL LOAD_DISPLAY1
		    DECFSZ COUNTER_DISPLAY, F
		    GOTO LOOP_DISPLAY
		    RETURN
    
LOAD_DISPLAY4	MOVF COUNTER_DISPLAY, W
		CALL TABLE_ON_DISPLAY_AC
		MOVWF PORTA
		MOVFW NTECLA4
		CALL TABLE_DECO_DISPLAY_AC
		MOVWF PORTD
		CALL DELAY_5MS
		RETURN
    
LOAD_DISPLAY3	MOVF COUNTER_DISPLAY, W
		CALL TABLE_ON_DISPLAY_AC
		MOVWF PORTA
		MOVFW NTECLA3
		CALL TABLE_DECO_DISPLAY_AC
		MOVWF PORTD
		CALL DELAY_5MS
		RETURN
    
LOAD_DISPLAY2	MOVF COUNTER_DISPLAY, W
		CALL TABLE_ON_DISPLAY_AC
		MOVWF PORTA
		MOVFW NTECLA2
		CALL TABLE_DECO_DISPLAY_AC
		MOVWF PORTD
		CALL DELAY_5MS
		RETURN
    
LOAD_DISPLAY1	MOVF COUNTER_DISPLAY, W
		CALL TABLE_ON_DISPLAY_AC
		MOVWF PORTA
		MOVFW NTECLA1
		CALL TABLE_DECO_DISPLAY_AC
		MOVWF PORTD
		CALL DELAY_5MS
		RETURN

DELAY_5MS	MOVLW   D'65'
		MOVWF   DELAY1
	LOOPA	MOVLW   D'25'
		MOVWF   DELAY2
	LOOPB	DECFSZ  DELAY2,F
		GOTO    LOOPB
		DECFSZ  DELAY1,F
		GOTO    LOOPA
		RETURN

TABLE_ON_DISPLAY_AC ADDWF PCL, F
		    RETLW b'11111111'
		    RETLW b'11111110'
		    RETLW b'11111101'
		    RETLW b'11111011'
		    RETLW b'11110111'
	    
TABLE_DECO_DISPLAY_AC	ADDWF PCL, F
			RETLW b'11000000'
			RETLW b'11111001'
			RETLW b'10100100'
			RETLW b'10110000'
			RETLW b'10011001'
			RETLW b'10010010'
			RETLW b'10000010'
			RETLW b'11111000'
			RETLW b'10000000'
			RETLW b'10011000'
			RETLW b'11111111'
			RETLW b'10000000'
			
END