    LIST P=16F887
    #include "p16f887.inc"
    
    __CONFIG _CONFIG1, _XT_OSC & _WDTE_OFF & _MCLRE_ON & _LVP_OFF

    CBLOCK 0X70
	COUNTER_DISPLAY
	DELAY1
	DELAY2
	CONT_NTECL
	NTECLA4
	NTECLA3
	NTECLA2
	NTECLA1
	W_TEMP
	STATUS_TEMP
	NTECL
    ENDC
    
    ORG 0X00
    GOTO INICIO
    ORG 0X04
    GOTO ISR_INICIO
    ORG 0X05
    
INICIO	
	BANKSEL TRISD		; (PORTD es digital por default)
	CLRF	TRISD		; PORTD Salida
	BANKSEL PORTD
	CLRF	PORTD		; PORTD estado bajo
	CLRF NTECLA4
	CLRF NTECLA3
	CLRF NTECLA2
	CLRF NTECLA1
	CLRF NTECL
	BANKSEL ANSELH		
	CLRF	ANSELH		; PORTB digital
	BANKSEL PORTB
	MOVLW B'11110000'			; PORTB estado bajo
	MOVWF PORTB
	BANKSEL OPTION_REG
	BCF OPTION_REG, NOT_RBPU    ;Habilito resistencias internas de pull-up
	BANKSEL TRISB
	MOVLW B'00001111'	
	MOVWF TRISB			; B<7,4>Salidas (columnas), B<3,0>Entradas (filas)
	BANKSEL ANSEL
	CLRF	ANSEL	    ; PORTA digital
	BANKSEL TRISA
	CLRF	TRISA	    ; PORTA salida
	BANKSEL PORTA
	CLRF	PORTA	    ; PORTA estado bajo
	BANKSEL IOCB
	MOVLW B'11111111'
	MOVWF IOCB
	BANKSEL INTCON
	BSF INTCON, RBIE	; Habilito interrupciones externas por PORTB
	BSF INTCON, GIE		; Habilito interrupciones del MCU
	MOVLW .4
	MOVWF CONT_NTECL

LOOP	CALL REFRESH_DISPLAYS
	GOTO LOOP
	
ISR_INICIO  MOVWF W_TEMP
	    SWAPF STATUS, W
	    MOVWF STATUS_TEMP
	    BCF INTCON, RBIE      ; deshabilita mientras atiende
	    MOVF PORTB, W         ; lectura para resetear latch
	    BCF INTCON, RBIF
	    
	    CALL TECL_PRESS
	    CALL TECL_LOAD
	    
ISR_FIN	    CLRF PORTB
	    MOVF PORTB, F
	    BCF INTCON, RBIF
	    BSF INTCON, RBIE      ; vuelve a habilitar interrupción
	    SWAPF STATUS_TEMP, W
	    MOVWF STATUS
	    SWAPF W_TEMP, F
	    SWAPF W_TEMP, W
	    RETFIE 
	    
TECL_PRESS  MOVLW B'01110000'
	    MOVWF PORTB
	    CALL DELAY_20MS ; TODO REVISAR. DICE ESTABILIZACION NOP (este delay es demasiado?)
	    CLRF NTECL
	    GOTO TEST_COL
	    
TEST_COL    	;Test c1
	    INCF NTECL, F
	    BTFSS PORTB, RB3
	    GOTO TECL_DELAY
		;Test c2
	    INCF NTECL, F
	    BTFSS PORTB, RB2
	    GOTO TECL_DELAY
		;Test c3
	    INCF NTECL, F
	    BTFSS PORTB, RB1
	    GOTO TECL_DELAY
		;Test c4
	    INCF NTECL, F
	    BTFSS PORTB, RB0
	    GOTO TECL_DELAY
	    GOTO TEST_FIL
	    
TEST_FIL    BTFSS PORTB, RB4
	    GOTO TECL_RST		;si ya probe todo termino la interrupcion
	    BSF STATUS, C		;sino recorro la siguiente fila
	    RRF PORTB
	    GOTO TEST_COL		;(columna por columna)
		RETURN
	    
TECL_RST    CLRF NTECL
	    GOTO ISR_FIN
	    ;RETURN				;vuelvo a linea 61: GOTO TECL_LOAD
	    
TECL_DELAY  CALL DELAY_20MS
		BTFSS PORTB, RB3	;loops antirrebote por software
	    GOTO $-1
	    BTFSS PORTB, RB2
	    GOTO $-1
	    BTFSS PORTB, RB1
	    GOTO $-1
	    BTFSS PORTB, RB0
	    GOTO $-1
	    BCF INTCON, RBIF	;bajo bandera de interrupcion
	    CLRF PORTB			;limpio puerto
	    RETURN				;vuelvo a linea 61: GOTO TECL_LOAD
	    
TECL_LOAD   MOVLW .4
	    SUBWF CONT_NTECL, W
	    BTFSC STATUS, Z
	    CALL LOAD_TECL4
	    MOVLW .3
	    SUBWF CONT_NTECL, W
	    BTFSC STATUS, Z
	    CALL LOAD_TECL3
	    MOVLW .2
	    SUBWF CONT_NTECL, W
	    BTFSC STATUS, Z
	    CALL LOAD_TECL2
	    MOVLW .1
	    SUBWF CONT_NTECL, W
	    BTFSC STATUS, Z
	    CALL LOAD_TECL1
	    
		DECFSZ CONT_NTECL,F
	    GOTO ISR_FIN
	    MOVLW .4
	    MOVWF CONT_NTECL
	    GOTO ISR_FIN
	    
LOAD_TECL4  MOVFW NTECL
	    MOVWF NTECLA4
	    RETURN
	    
LOAD_TECL3  MOVFW NTECL
	    MOVWF NTECLA3
	    RETURN
	    
LOAD_TECL2  MOVFW NTECL
	    MOVWF NTECLA2
	    RETURN
	    
LOAD_TECL1  MOVFW NTECL
	    MOVWF NTECLA1
	    RETURN
	    
; *** igual al TP anterior ***
REFRESH_DISPLAYS    MOVLW .4
		    MOVWF COUNTER_DISPLAY
LOOP_DISPLAY	    MOVLW .4
		    SUBWF COUNTER_DISPLAY, W
		    BTFSC STATUS, Z
		    CALL LOAD_DISPLAY4
		    MOVLW .3
		    SUBWF COUNTER_DISPLAY, W
		    BTFSC STATUS, Z
		    CALL LOAD_DISPLAY3
		    MOVLW .2
		    SUBWF COUNTER_DISPLAY, W
		    BTFSC STATUS, Z
		    CALL LOAD_DISPLAY2
		    MOVLW .1
		    SUBWF COUNTER_DISPLAY, W
		    BTFSC STATUS, Z
		    CALL LOAD_DISPLAY1
		    DECFSZ COUNTER_DISPLAY, F
		    GOTO LOOP_DISPLAY
		    RETURN
    
LOAD_DISPLAY4	MOVF COUNTER_DISPLAY, W
		CALL TABLE_ON_DISPLAY_AC
		MOVWF PORTA
		MOVFW NTECLA4
		CALL TABLE_DECO_DISPLAY_AC
		MOVWF PORTD
		CALL DELAY_5MS
		RETURN
    
LOAD_DISPLAY3	MOVF COUNTER_DISPLAY, W
		CALL TABLE_ON_DISPLAY_AC
		MOVWF PORTA
		MOVFW NTECLA3
		CALL TABLE_DECO_DISPLAY_AC
		MOVWF PORTD
		CALL DELAY_5MS
		RETURN
    
LOAD_DISPLAY2	MOVF COUNTER_DISPLAY, W
		CALL TABLE_ON_DISPLAY_AC
		MOVWF PORTA
		MOVFW NTECLA2
		CALL TABLE_DECO_DISPLAY_AC
		MOVWF PORTD
		CALL DELAY_5MS
		RETURN
    
LOAD_DISPLAY1	MOVF COUNTER_DISPLAY, W
		CALL TABLE_ON_DISPLAY_AC
		MOVWF PORTA
		MOVFW NTECLA1
		CALL TABLE_DECO_DISPLAY_AC
		MOVWF PORTD
		CALL DELAY_5MS
		RETURN

DELAY_5MS	MOVLW   D'65'
		MOVWF   DELAY1
LOOPA		MOVLW   D'25'
		MOVWF   DELAY2
LOOPB		DECFSZ  DELAY2,F
		GOTO    LOOPB
		DECFSZ  DELAY1,F
		GOTO    LOOPA
		RETURN
		
DELAY_20MS	MOVLW   D'255'
		MOVWF   DELAY1
LOOP1		MOVLW   D'26'
		MOVWF   DELAY2
LOOP2		DECFSZ  DELAY2,F
		GOTO    LOOP2
		DECFSZ  DELAY1,F
		GOTO    LOOP1
		RETURN

TABLE_ON_DISPLAY_AC ADDWF PCL, F
		    RETLW b'11111111'
		    RETLW b'11111110'
		    RETLW b'11111101'
		    RETLW b'11111011'
		    RETLW b'11110111'
	    
TABLE_DECO_DISPLAY_AC	ADDWF PCL, F
			RETLW b'11111111' ;off
			RETLW b'11111001' ;1
			RETLW b'10100100' ;2
			RETLW b'10110000' ;3
			RETLW b'10100000' ;a
			RETLW b'10011001' ;4
			RETLW b'10010010' ;5
			RETLW b'10000010' ;6
			RETLW b'10000011' ;b
			RETLW b'11111000' ;7
			RETLW b'10000000' ;8
			RETLW b'10011000' ;9
			RETLW b'11000110' ;c
			RETLW b'10001001' ;* (x)
			RETLW b'11000000' ;0
			RETLW b'10001011' ;# (h)
			RETLW b'10100001' ;d
			

    END





