LIST P=16F887
#include "p16f887.inc"


	ORG 0x00
	GOTO INICIO
INICIO	ORG 0x05
	
	BSF STATUS, RPO
	BSF STATUS, RP1   ; BANK 3
	BCF ANSEL,  ANS5  ; RE5 DIGITAL
	BCF ANSELH, ANS12 ; RB0 DIGITAL
	BCF ANSELH, ANS10 ; RB1 DIGITAL
	BCF ANSELH, ANS8  ; RB2 DIGITAL
	BCF ANSELH, ANS9  ; RB3 DIGITAL
	BCF ANSELH, ANS11 ; RB4 DIGITAL
	BCF ANSELH, ANS13 ; RB5 DIGITAL
			  ; RB6 DIGITAL
			  ; RB7 DIGITAL
        BCF STATUS, RP1   ; BANK 1
        BSF TRISE, TRISE0 ; RE0 ENTRADA
	BCF TRISB, TRISB0 ; RB0 SALIDA
	BCF TRISB, TRISB1 ; RB1 SALIDA
	BCF TRISB, TRISB2 ; RB2 SALIDA
	BCF TRISB, TRISB3 ; RB3 SALIDA
	BCF TRISB, TRISB4 ; RB4 SALIDA
	BCF TRISB, TRISB5 ; RB5 SALIDA
	BCF TRISB, TRISB6 ; RB6 SALIDA
	BCF TRISB, TRISB7 ; RB7 SALIDA
	BCF STATUS, RP0   ; BANK 0
	BCF PORTE, RE0	  ; RE0 LOW
	BCF PORTB, RB0	  ; RB0 LOW
	BCF PORTB, RB1    ; RB1 LOW
	BCF PORTB, RB2    ; RB2 LOW
	BCF PORTB, RB3    ; RB3 LOW
	BCF PORTB, RB4    ; RB4 LOW
	BCF PORTB, RB5    ; RB5 LOW
	BCF PORTB, RB6    ; RB6 LOW
	BCF PORTB, RB7    ; RB7 LOW
	